### ISSUE TITLE
TA Form: Show traveler information (name, dept, etc.)

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#55]
# Context

Original Info
> Need the ability to enter and submit a travel auth form on behalf of someone in the organization.  Therefore the app needs to show the traveler information as part of the request.  In addition we are are leveraging the directory api to automate the traveler name and department/ branch etc. fields this information is sometime incorrect.  So we want to surface the information in the case this information is incorrect and the traveler needs to change it.

## Breakdown

- [x] #91
  - [x] ~Once profile edit features exist, add link on the VUser component to the profile edit page~ Linked to profile page, dropping profile edit feature for now
- [ ] Build out an admin interface that lets a `supervisor/admin?` create a travel request for a user other than themself. 
    - see [#87](https://github.com/icefoganalytics/travel-authorization/issues/87) for admin "manage" view.
    - See https://github.com/icefoganalytics/travel-authorization/issues/166
- [x] Check that travel authorization creation by non-admins injects user information on the back-end, rather than permitting it being sent from the front-end
- [x] Check that travel authorization creation, by any user type, always stores the creator's user id.

Add system to profile page to:
- [x] view your full profile information
- [x] fetch/sync your full profile information from the government directory
- [ ] ability to edit the profile information, as the current user - and potentially block syncing? maybe add a toggle that turns off auto-sync if you manually edit your profile, and turns on auto-sync if you ever run a force sync?
- [ ] ability to edit the user information of another user, as an admin

**Comment by klondikemarlen** [comment]
This might end up being a major feature in its own right. Much of the current system, and original system as well is tied to the "current user".

i.e. from a security perspective, the creator of the form is set in the back-end, rather than selectable in the front-end.

I'll have to do some analysis on this, and write out the list of changes we'd need to support this.

**Comment by klondikemarlen** [comment]
Probably best to break this into two features:

1. Creating a travel authorization for someone else - Admin interface?
2. Editing you personal department/branch/unit, etc. fields in case this information is incorrect - I believe we may have solved this at Proof by deferring to the directory api. i.e. telling users that if they want their information to be correct, they should update their information at the external portal.

@dpdavids thoughts?

**Comment by klondikemarlen** [comment]
I'm going to defer this for now, by building out the most basic Profile view, that shows general user information, with a once day sync of profile information with the government directory. I'll also add a button to the users profile so they can force a sync. See https://github.com/icefoganalytics/travel-authorization/issues/88

**Comment by klondikemarlen** [comment]
After some reflection I can convert the user's name field into a hoverable `v-chip` that on hover shows more detailed user info, the panel that gets opened should have an "edit" button that links to the user's profile page where they can update their info.

![image](https://github.com/icefoganalytics/travel-authorization/assets/23045206/3095d2ab-f1bd-4b6b-9c65-864a0ea8634d)

Basically an effect like hovering on a github issue like this:
![image](https://github.com/icefoganalytics/travel-authorization/assets/23045206/55171ed7-66bb-49fc-b0d5-01b2e2114fa8)

**Comment by dpdavids** [comment]
@klondikemarlen let's stick with the Proof solution for now "I believe we may have solved this at Proof by deferring to the directory api. i.e. telling users that if they want their information to be correct, they should update their information at the external portal."

**Comment by klondikemarlen** [comment]
Closing as broken out into other tickets.
