### ISSUE TITLE
Epic for Travel Authorization Expenses

### ISSUE THREAD

**Issue by klondikemarlen** [icefoganalytics/travel-authorization#62]
# Context

This is a list of all tasks related to travel authorization expenses.

### Travel Auth (request approval)
- [ ] Create a new or edit an existing travel authorization request (where edit = draft)
    - [ ] Define the travel steps
    - [ ] Define the travel method
    - [ ] Define the final destination
    - [ ] Define the purpose of travel
- [ ] Request a travel advance
- [ ] Have the system create an estimate of my trip
- [ ] Edit the estimates
- [ ] Define if my travel was on the preapproved travel list
- [ ] Route the approval to my supervisor
- [] ~Enter GL coding for my travel if I know it (may have multiple codes)~ - out of scope
- [ ] Validate the GL code is a valid #

### Travel Auth Status view
- [ ] See the status of my travel auth requests

### Travel Auth (after approval)
- [ ] Receive notification that travel has been approved
- [ ] Request travel desk support (flights)
- [ ] ~Request pool vehicle (open FVRS tool at minimum [FVRS Tool](https://apps.ynet.gov.yk.ca/fvrs/f?p=410:101::::::), if can push info from travel auth to APEX form) ~ out of scope

### Expense (During travel)
- [ ] Copy my estimates for reimbursement to my expenses list (excluding flights)
- [ ] Edit an existing expense
- [ ] Add a new expense (including type, description, and amount)
- [ ] Upload a receipt to an expense
- [ ] System to calculate my per diems based on my entered travel dates and times
- [ ] Enter the exact times to my travel to account for flight delays or unscheduled changes; if changed, need to provide a rationale

### Expense (after travel)
- [ ] Enter expenses as above
- [ ] ~Affidavit of lost receipt (need to define if this can be a digital approval); for now, just upload as receipt~ - out of scope
- [ ] Submit my travel claim to my supervisor for approval
- [ ] Have the total cost reflect my travel advance
- [ ] Enter GL coding for my travel if I know it (may have multiple codes)
- [ ] ~Print a PDF of the report~ - out of scope
- [ ] ~Upload a signed document~ - out of scope

### Expense Status view
- [ ] See the status of my expense claim

### Travel Report
- [ ] ~Ensure it is filled out if travel is out of territory~ - out of scope
- [ ] ~Print a PDF of the report~ - out of scope
- [ ] Upload a memo
